#!/bin/sh

echo Content-type: text/html
echo ""

cat <<EOF
<!DOCTYPE html>
<html>
<head>
<title>Info</title>
<meta charset="utf-8"/>
<style type="text/css">
* {
    margin: 0;
}

html, body {
    height: 98%;
}

#header {
	margin:1%;
}

#footer {
    position: absolute;
    bottom: 1%;
    left: 1%;
    right: 1%;
    width: 98%;
}
</style>
</head>
<body>
<div id="header">
EOF

name=$(uci get -q freifunk.@settings[0].name)
[ -n "$name" ] && echo "<b>Name: $name</b><br />"

echo "<b>Eigene IPv4-Adresse: </b>"
ip -4 address show dev br-public 2> /dev/null | tr '/' ' '| awk '/inet/{ print($2); exit(0);}'

echo "<br /><b>Eigene IPv6-Adresse: </b>"
ip -6 address show dev br-public 2> /dev/null | tr '/' ' '| awk '/inet/{ print($2); exit(0);}'

echo "<br /><b>Anzahl bekannter Knoten: </b>"
echo $((`batctl tg | grep '^ \*' | cut -b 33-49 | sort | uniq | wc -l 2> /dev/null`+1))

echo "<br /><b>Anzahl benachbarter Knoten: </b>"
batctl o | grep '^[[:digit:]|[:lower:]]' | cut -b 37-53 | sort | uniq | wc -l

echo "<br /><br />"

max=$(uci get -q freifunk.@settings[0].service_display_max)


if [ -n "$max" -a "$max" != "0" ]; then
	link_list=$(
		printf "$(alfred -r 91)" | head -$max | awk -F'["\\]+' '{ if($5 == "link" && $7 ~ /^[][ [:alnum:]_\/.:]{3,60}$/ && $9 == "label" && $11 ~ /^[][ [:alnum:]_\/.:]{3,30}$/) printf("<li><a href=\"%s\">%s</a></li>\n", $7, $11) }'
	)
	echo "<b>Liste lokaler Angebote im Freifunk-Netz:</b>"
	echo "<br /><br />"
	echo "<ul>"
	[ -n "$link_list" ] && echo "$link_list" || echo "<li>Keine Angebote gefunden.</li>"
	echo "</ul>"
	echo "<br />"

	[ -n "$link_list" ] && echo "(Bitte beachten: Diese Eintr&auml;ge stammen nicht von diesem Router!)"
fi

cat <<EOF
</div>

<div id="footer">
    <span style="float: left;"><a href="#" id="link">Login</a></span>
    <span style="float: right;"><a href="http://www.freifunk-bielefeld.de/">FFBI Firmware</a> v$(uci get -q freifunk.@settings[0].version || echo "???")</span>
</div>

<script type="text/javascript">
document.getElementById("link").href="https://"+location.host;
</script>

</body>
</html>
EOF
