#!/bin/sh /etc/rc.common
# Copyright (C) 2013 Project Gluon

START=95


prefix4=`uci get freifunk.@settings[0].prefix4`
prefix6=`uci get freifunk.@settings[0].prefix6`

next_node_mac='16:41:95:40:f7:dc'
next_node_ip4="${prefix4%0*}1"
next_node_ip6="${prefix6%/*}1"


ebtable_apply() {
	cmd="$@"

	$cmd FORWARD --logical-out br-public -o bat0 -d $next_node_mac -j DROP
	$cmd OUTPUT --logical-out br-public -o bat0 -d $next_node_mac -j DROP
	$cmd FORWARD --logical-out br-public -o bat0 -s $next_node_mac -j DROP
	$cmd OUTPUT --logical-out br-public -o bat0 -s $next_node_mac -j DROP

	$cmd FORWARD --logical-out br-public -o bat0 -p IPv4 --ip-destination $next_node_ip4 -j DROP
	$cmd OUTPUT --logical-out br-public -o bat0 -p IPv4 --ip-destination $next_node_ip4 -j DROP
	$cmd FORWARD --logical-out br-public -o bat0 -p IPv4 --ip-source $next_node_ip4 -j DROP
	$cmd OUTPUT --logical-out br-public -o bat0 -p IPv4 --ip-source $next_node_ip4 -j DROP

	$cmd FORWARD --logical-out br-public -o bat0 -p IPv6 --ip6-destination $next_node_ip6 -j DROP
	$cmd OUTPUT --logical-out br-public -o bat0 -p IPv6 --ip6-destination $next_node_ip6 -j DROP
	$cmd FORWARD --logical-out br-public -o bat0 -p IPv6 --ip6-source $next_node_ip6 -j DROP
	$cmd OUTPUT --logical-out br-public -o bat0 -p IPv6 --ip6-source $next_node_ip6 -j DROP
}

start() {
	ebtable_apply 'ebtables -A'
}

stop() {
	ebtable_apply 'ebtables -D'
}
