#!/bin/sh

# Make sure that the ULA address is based on the
# MAC address of the primary batman-adv interface.

if [ "$INTERFACE" = "bat0" ]; then
	. /lib/ff_shared.sh

	macaddr="$(cat /sys/kernel/debug/batman_adv/bat0/originators | awk -F'[/ ]' '{print $7; exit;}')"
	ipaddr="$(ula_addr $macaddr)"
	ip a a "$ipaddr/64" dev br-freifunk
fi
