#!/bin/sh /etc/rc.common

START=19


start()
{
exec >/tmp/freifunk_first.log 2>&1
. /sbin/freifunk_shared

if [ -f /etc/rc.d/S50telnet ]; then
    echo "(I) Freifunk: skip and wait for setup to be run"
    exit
fi

echo "(I) Freifunk: start freifunk_first"


mac=`uci get -q freifunk.settings.mac`
share_internet=`uci get -q freifunk.settings.share_internet`
config_nets=`uci get -q freifunk.settings.config_nets`

echo "(I) Freifunk: mac: '$mac'"
echo "(I) Freifunk: share_internet: '$share_internet'"
echo "(I) Freifunk: config_nets: '$config_nets'"


#Create dummy interfaces to be able to set the mac of
#br-mesh and the mac for the OGMs of batman-adv freely.
#Also, a bridge needs at least one interface.

echo "(I) Freifunk: Create dummy_mesh interface."
tunctl -t dummy_mesh > /dev/null
ifconfig dummy_mesh hw ether $mac up

echo "(I) Freifunk: Create dummy_bat interface."
tunctl -t dummy_bat > /dev/null
ifconfig dummy_bat hw ether $mac up

echo "(I) Freifunk: Create dummy_lan interface."
tunctl -t dummy_lan > /dev/null
ifconfig dummy_lan hw ether $mac up


if [ "$share_internet" = "yes" ]; then
    #forward from mesh to wan
    s=firewall.`uci add firewall forwarding`
    uci set $s.src="mesh"
    uci set $s.dest="wan"
fi


#filter ssh/https ports
for src in wan lan mesh; do
  default_target=`uci_query "-q get firewall.@zone[?].name" "$src" "input"`
  ff_contains "$config_nets" "$src" && target=ACCEPT || target=REJECT
  [ "$target" = "$default_target" ] && continue
  for port in 22 443; do
    s=firewall.`uci add firewall rule`
    uci set $s.src=$src
    uci set $s.dest_port=$port
    uci set $s.target=$target
    uci set $s.proto=tcp
  done
done


echo "(I) Freifunk: done freifunk_first"
}
