#!/bin/sh /etc/rc.common

START=19


#allow/block access via ssh/https
config_access() {
	local default_target src port s

	find_default_target() {
		local s="$1" src="$2" n=""
		config_get n "$s" name
		[ "$src" == "$n" ] && { config_get default_target "$s" input; return 1; }
	}

	#filter ssh/https ports
	config_load firewall
	for src in wan private public; do
		default_target=""
		config_foreach find_default_target 'zone' $src
		list_contains config_nets "$src" && target=ACCEPT || target=REJECT
		[ "$target" = "$default_target" ] && continue
		for port in 22 443; do
			s=firewall.`uci add firewall rule`
			uci set $s.src=$src
			uci set $s.dest_port=$port
			uci set $s.target=$target
			uci set $s.proto=tcp
		done
	done
}

start()
{
exec >/tmp/freifunk_init.log 2>&1
. /lib/functions.sh


if [ -f /etc/init.d/freifunk_setup ]; then
	echo "(I) Freifunk: Skip and wait for /etc/init.d/freifunk_setup to be run."
	exit
fi

echo "(I) Freifunk: start freifunk_init"


mac=`uci get -q freifunk.@settings[0].mac`
share_internet=`uci get -q freifunk.@settings[0].share_internet`
config_nets=`uci get -q freifunk.@settings[0].config_nets`

echo "(I) Freifunk: mac: '$mac'"
echo "(I) Freifunk: share_internet: '$share_internet'"
echo "(I) Freifunk: config_nets: '$config_nets'"


#Create a dummy interface to be able to set the
#MAC address for the OGMs of batman-adv freely.

echo "(I) Freifunk: Create dummy_mesh interface."
tunctl -t dummy_mesh > /dev/null


#add first interface to set originator mac
ip link set dev dummy_mesh down
ip link set dev dummy_mesh address $mac mtu 1426 up
batctl if add dummy_mesh


uci delete -q firewall.share_internet
if [ "$share_internet" = "yes" ]; then
	#forward from public to wan
	uci set firewall.share_internet="forwarding"
	uci set firewall.share_internet.src="public"
	uci set firewall.share_internet.dest="wan"
fi

config_access

echo "(I) Freifunk: done freifunk_init"
}
