#!/bin/sh /etc/rc.common

START=96


start ()
{
#write everything from stdout and stderr to a log file
exec >/tmp/freifunk_last.log 2>&1

echo "(I) Freifunk: start freifunk_last"


if [ -f /etc/rc.d/S50telnet ]; then
  echo "(I) Freifunk: setup start"
  /sbin/freifunk_setup
  echo "(I) Freifunk: setup end"
  reboot #todo: work without reboot here
fi

#Set the mac of br-mesh explicitly so it is fixed.
#A bridge may change to the lowest may mac otherwise.
mesh_mac=`uci get freifunk.settings.mac`
echo "(I) Freifunk: set MAC of br-mesh to '$mesh_mac'"
ifconfig br-mesh hw ether $mesh_mac

mesh_ip=`mac2ip $mesh_mac`
echo "(I) Freifunk: set IP for br-mesh to '$mesh_ip'"
uci set network.mesh.ipaddr="$mesh_ip"
ifconfig br-mesh $mesh_ip

echo "(I) Freifunk: restart /etc/init.d/dnsmasq"
/etc/init.d/dnsmasq restart

echo "(I) Freifunk: call wan_watchdog to check for internet"
/sbin/wan_watchdog

echo "(I) Freifunk: done feifunk_last"
}
