#!/bin/sh /etc/rc.common

START=96

#boot () {

start () {

#write everything from stdout and stderr to a log file
exec >/tmp/freifunk.log 2>&1
date

#abort if /etc/config/freifunk doesn's exist
if [ ! -f /etc/config/freifunk ]; then
    echo "/etc/config/freifunk not found"
    exit
fi


ah_ssid=`uci get freifunk.settings.ah_ssid`
ap_ssid=`uci get freifunk.settings.ap_ssid`

wifi_interface=`uci get freifunk.settings.wifi_interface`
wifi_device=`uci get freifunk.settings.wifi_device`

wan_interface=`uci get freifunk.settings.wan_interface`
lan_interface=`uci get freifunk.settings.lan_interface`


echo "ah_ssid: '$ah_ssid'"
echo "ap_ssid: '$ap_ssid'"
echo "wifi_interface: '$wifi_interface'"
echo "wifi_device: '$wifi_device'"
echo "wan_interface: '$wan_interface'"
echo "lan_interface: '$lan_interface'"


echo "get lan interface"
if [ -z "$lan_interface" ]; then
    lan_interface=`uci get network.@switch_vlan[0].device`
    if [ -z "$lan_interface" ]; then
        echo "Cannot get lan_interface"
        exit
    else
        uci set freifunk.settings.lan_interface=$lan_interface
        uci commit freifunk
    fi
fi

echo "get wan interface"
if [ -z "$wan_interface" ]; then
    wan_interface=`uci get network.wan.ifname`
    if [ -z "$wan_interface" ]; then
        echo "Cannot get wan_interface"
        exit 1
    else
        uci set freifunk.settings.wan_interface=$wan_interface
        uci commit freifunk
    fi
fi


if  [ -f /etc/rc.d/S60dnsmasq ]; then
    /etc/init.d/dnsmasq stop
    /etc/init.d/dnsmasq disable
fi

if  [ -f /etc/rc.d/S65nodogsplash ]; then
    /etc/init.d/nodogsplash stop
    /etc/init.d/nodogsplash disable
fi

if  [ -f /etc/rc.d/S90batman-adv ]; then
    /etc/init.d/batman-adv stop
    /etc/init.d/batman-adv disable
fi

wan_mac=$(ifconfig $wan_interface | grep HWaddr | awk '{print $5}')
echo "wan_mac '$wan_mac'"

let x=29
let y=0x${wan_mac:12:2}                             
let z=0x${wan_mac:15:2}                      
mesh_ip="10.$x.$y.$z"
echo "mesh_ip '$mesh_ip'"


# default configuration on first boot
if [ "$mesh_ip" != `uci -q get network.mesh.ipaddr` ]; then
    
    ## /etc/config/network ##
    echo "setup /etc/config/network"
    uci -q delete network.lan
    uci -q delete network.mesh
    uci set network.mesh="interface"
    uci set network.mesh.type="bridge"
    uci set network.mesh.ifname="bat0 $lan_interface"
    uci set network.mesh.mtu="1527"
    uci set network.mesh.ipaddr="$mesh_ip"
    uci set network.mesh.proto=static
    uci set network.mesh.netmask="255.0.0.0"
    uci commit network

    echo "get wifi_device"
    if [ -z "$wifi_device" ]; then
        wifi_device=`uci get wireless.@wifi-iface[0].device` #`uci show wireless | awk '/=wifi-device/ {print}'`
        if [ -z "$wifi_device" ]; then
            echo "Cannot get wifi_device"
            exit
        else
            uci set freifunk.settings.wifi_device=$wifi_device
            uci commit freifunk
        fi
    fi
    
    echo "setup /etc/config/wireless"
    ## /etc/config/wireless ##
    uci set wireless.$wifi_device.channel=1

    #remove all wifi_interface entries
    while uci -q delete wireless.@wifi-iface[0]; do :; done
    
    #AdHoc for batman
    uci add wireless wifi-iface
    uci set wireless.@wifi-iface[-1].device="$wifi_device"
    uci set wireless.@wifi-iface[-1].mode=adhoc
    uci set wireless.@wifi-iface[-1].ssid="$ah_ssid"
    uci set wireless.@wifi-iface[-1].bssid="12:CA:FF:EE:BA:BE"
    uci set wireless.@wifi-iface[-1].hidden=1

    #AccessPoint for clients
    uci add wireless wifi-iface
    uci set wireless.@wifi-iface[-1].device="$wifi_device"
    uci set wireless.@wifi-iface[-1].mode=ap
    uci set wireless.@wifi-iface[-1].network=mesh
    uci set wireless.@wifi-iface[-1].ssid="$ap_ssid"
    
    #wireless is disabled by default
    uci -q delete wireless.@wifi-device[0].disabled

    #uci commit wireless
    uci commit wireless
    
    echo "wireless down/up"
    wifi down
    wifi up
    
    echo "setup /etc/config/dhcp"
    uci set dhcp.mesh.start=$((256*256*$x+1))
    uci set dhcp.mesh.limit=$((255*255+253))
    uci commit dhcp
    
    echo "get wifi interface"
    if [ -z "$wifi_interface" ]; then
        wifi_interface=`iwconfig 2> /dev/null | awk "/$ah_ssid/ { print \\$1 }"`
        if [ -z "$wifi_interface" ]; then
            echo "Cannot get wifi_interface"
            exit 1
        else
            uci set freifunk.settings.wifi_interface=$wifi_interface
            uci commit freifunk
        fi
    fi
    
    if [ -z "$ah_ssid" -o -z "$ap_ssid" ]; then
        echo "ah_ssid and ap_ssid required"
        exit 1
    fi

    if [ "$ah_ssid" == "$ap_ssid" ]; then
        echo "ah_ssid and ap_ssid need to be different"
        exit 1
    fi
fi


echo "restart /etc/init.d/network"
/etc/init.d/network restart             

echo "restart /etc/init.d/dnsmasq"
/etc/init.d/dnsmasq restart


wan_ip=$(route -n | grep 'UG' | awk '{ print $2}')
echo "wan_ip: '$wan_ip'"

#for batman
ifconfig $wifi_interface mtu 1527

IPCHECK="192.33.4.12 128.8.10.90 193.0.14.129 198.41.0.4 192.228.79.201 192.5.5.241 192.36.148.17 192.58.128.30"
if [ $(fping -a $IPCHECK 2> /dev/null | wc -l) != 0 ]; then
    echo "Configure node as gateway."
    if [ -n `uci get n2n.@edge[0].key` ]; then
        echo "Eintrag in /etc/config/n2n gefunden. Starte VPN Tunnel."
        /etc/init.d/n2n restart
        sleep 20
    fi
    
    echo "restart /etc/init.d/nodogsplash"
    /etc/init.d/nodogsplash restart
    
    # Batman Server Mode
    uci set batman-adv.bat0.interfaces="$wifi_interface"
    uci set batman-adv.bat0.gw_mode=server
else
    echo "Configure node as client."
    
    # Batman Client Mode
    uci set batman-adv.bat0.interfaces="$wifi_interface"
    uci set batman-adv.bat0.gw_mode=client
    
fi
uci commit batman-adv
uci commit batman-adv

echo "restart /etc/init.d/batman-adv "
/etc/init.d/batman-adv restart


echo "###################"
echo "ah_ssid: '$ah_ssid'"
echo "ap_ssid: '$ap_ssid'"
echo "wifi_interface: '$wifi_interface'"
echo "wifi_device: '$wifi_device'"
echo "mesh_ip: '$mesh_ip'"
echo "wan_interface: '$wan_interface'"
echo "lan_interface: '$lan_interface'"
}

stop () {
    /etc/init.d/nodogsplash stop
    /etc/init.d/batman-adv stop
    /etc/init.d/dnsmasq stop
}

