#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1

start_instance() {
	procd_open_instance
	procd_set_param command /usr/sbin/simple-radvd $*
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	start_instance -i br-freifunk -p $(uci get network.globals.ula_prefix)
	start_instance -i br-lan -p $(uci get network.globals.ula_prefix)
}
