#!/bin/ash

LOG=/tmp/check_ip.log
date > $LOG

mesh_ip=`ifconfig br-mesh | grep "inet" | awk 'BEGIN { FS=":" } { print $2 }' | awk '{ print $1 }'`

echo "Current IP: '$mesh_ip'" >> $LOG

#check if existing ip is ok
if [ ! -z "$mesh_ip" ]; then
  arping -D -f -q -I br-mesh -c 2 $mesh_ip
  if [ $? -eq 0 ]; then
    echo "IP is ok, no change: '$mesh_ip'" >> $LOG
    exit 0
  fi
fi


x=1
while [ $x -le 254 ]
do
  arping -D -f -q -I br-mesh -c 2 10.29.$x.1
  if [ $? -eq 0 ]; then
      echo "Found IP: '10.29.$x.1'" >> $LOG
      break
  fi
  x=$(( $x + 1 ))
done

if [ $x -eq 255 ]; then
  echo "Cannot find free IP."  >> $LOG
  exit
fi

echo "Use new IP: '10.29.$x.1'" >> $LOG

#ifconfig br-mesh 10.29.$x.1
uci set network.mesh.ipaddr="10.29.$x.1"
uci set network.mesh.proto=static
uci set network.mesh.netmask="255.255.0.0"
uci commit network

uci set dhcp.mesh.start_ip="10.29.$x.2"
uci set dhcp.mesh.end_ip="10.29.$x.254"
uci commit dhcp
    
ifconfig br-mesh 10.29.$x.1
/etc/init.d/dnsmasq start
#/etc/init.d/network start


