#!/bin/sh


get_ip() {
  ifconfig "$1" 2> /dev/null | grep "inet addr" | awk 'BEGIN { FS=":" } { print $2 }'| awk '{ print $1 }'
}

#query query_name match_value [get_other_value]
uci_query()
{
  local query=$1
  local value=$2
  local other=$3
  local i=0
  while true; do
    local q=${query/\?/$i}
    v=`uci $q 2> /dev/null`
    [ $? -ne 0 ] && return
    [ "$v"  = "$value" ] && {
      [ -n "$other" ] && echo `uci ${q%.*}.$other 2> /dev/null` || echo $i
      return
    }
    i=$(($i + 1))
  done
}
