#!/bin/sh

#Set an IP for br-mesh.

exec >/tmp/ip_watchdog.log 2>&1
date

echo "(I) ip_watchdog: start"

debug=`uci get -q freifunk.settings.debug`

mesh_ip=`ifconfig br-mesh | grep "inet addr" | awk 'BEGIN { FS=":" } { print $2 }'| awk '{ print $1 }'`
mesh_mac=$(ifconfig br-mesh | grep HWaddr | awk '{print $5}')

echo "(D) ip_watchdog: br-mesh interface ip: '$mesh_ip'"
echo "(D) ip_watchdog: br-mesh interface mac: '$mesh_mac'"

if [ -z "$mesh_ip" ]; then
    mesh_ip=`mac2ip $mesh_mac`
    echo "(I) ip_watchdog: set new IP: '$mesh_ip'"
    uci set network.mesh.ipaddr="$mesh_ip"
    ifconfig br-mesh $mesh_ip
else
    echo "(I) ip_watchdog: nothing to do"
fi

echo "(I) ip_watchdog: done"
