#!/bin/sh

#Get the IP of a node by MAC.

mac=$1
prefix4=`uci get -q freifunk.@settings[0].prefix4`

[ -z "$mac" -o -z "$prefix4" -o ${#mac} -ne 17 ] && exit 1

seed=0
for x in $(echo $mac | tr ":" "\n"); do
	seed=$((seed + 0x$x + (0x$x << 8) + (0x$x << 16)))
done

addr_t=$((1900545 + (seed % 65278)))
addr_c=$(((addr_t & 0xff00) >> 8))
addr_d=$(((addr_t & 0x00ff) >> 0))

echo "${prefix4%%.0*}.$addr_c.$addr_d"
