#!/bin/sh

#Get the IP of a node by MAC.

mac=$1
ff_subnet=`uci get -q freifunk.settings.ff_subnet`
start_ip=`uci get dhcp.mesh.start`
end_ip=`uci get dhcp.mesh.limit`

[ -z "$mac" -o -z "$ff_subnet" -o  -z "$start_ip" -o -z "$end_ip" -o ${#mac} -ne 17 ] && {
    echo "0.0.0.0"
    exit 1
}

seed=0
for x in $(echo $mac | tr ":" "\n"); do
    seed=$((seed + 0x$x + (0x$x << 8) + (0x$x << 16)))
done

addr_t=$((start_ip + (seed % end_ip)))
addr_c=$(((addr_t & 0xff00) >> 8))
addr_d=$(((addr_t & 0x00ff) >> 0))

echo "10.$ff_subnet.$addr_c.$addr_d"
