#!/bin/sh

#set the gateway dnsmasq delivers via dhcp leases

exec >/tmp/set_gateway.log 2>&1
date

echo "(I) set_gateway: start set_gateway"


arg_if="$1" #mesh or wan
arg_gw="$2" #gateway ip

pre_local_gw=`cat /tmp/ff_local_gw 2> /dev/null`
pre_mesh_gw=`cat /tmp/ff_mesh_gw 2> /dev/null`

echo "(I) set_gateway: arg_if: '$arg_if', arg_gw: '$arg_gw'"


#set gw value for lan setting
lan_gw() {
    lan_str="121,10.0.0.0/8,192.168.1.1"
    [ -n "$1" ] && lan_str="$lan_str,0.0.0.0/0,$1"
}

#set gw value for mesh setting
mesh_gw() {
    [ -n "$1" ] && mesh_str="3,$1" ||  mesh_str="3"
}


if [ "$arg_if" = "mesh" ]
then #called by /etc/hotplug.d/net/11-batman
    mesh_gw="$arg_gw"
    local_gw=$pre_local_gw
else #called by /sbin/wan_watchdog
    mesh_gw=$pre_mesh_gw
    local_gw="$arg_gw"
fi

echo "(I) set_gateway: pre_mesh_gw: '$pre_mesh_gw', pre_local_gw: '$pre_local_gw'"

[ "$pre_mesh_gw" == "$mesh_gw" -a "$pre_local_gw" == "$local_gw" ] && {
  echo "(I) set_gateway: Nothing to change. - done"
  exit 0
}

echo "(I) set_gateway: mesh_gw: '$mesh_gw', local_gw: '$local_gw'"

echo -n "$local_gw" > /tmp/ff_local_gw
echo -n "$mesh_gw" > /tmp/ff_mesh_gw

#set gateway to annouce in lan and mesh
share_wan=`uci get -q freifunk.settings.share_wan`
if [ -n "$local_gw" ]; then
  if [ "$share_wan" = "yes" ]; then
    lan_gw "$local_gw"
    mesh_gw "$local_gw"
  else
    lan_gw "$local_gw"
    mesh_gw "$mesh_gw"
  fi
else
  if [ "$share_wan" = "yes" ]; then
    lan_gw "$mesh_gw"
    mesh_gw "$mesh_gw"
  else
    lan_gw "$mesh_gw"
    mesh_gw "$mesh_gw"
  fi
fi

uci set dhcp.mesh.dhcp_option="$mesh_str"
uci set dhcp.lan.dhcp_option="$lan_str"

/etc/init.d/dnsmasq restart

echo "(I) set_gateway: done"
