#!/bin/sh

#set the gateway dnsmasq delivers via dhcp leases

exec >/tmp/set_gateway.log 2>&1
date

echo "(I) set_gateway: start set_gateway"


arg_if="$1" #mesh or wan
arg_gw="$2" #gateway ip

pre_local_gw=`cat /tmp/ff_local_gw 2> /dev/null`
pre_mesh_gw=`cat /tmp/ff_mesh_gw 2> /dev/null`

echo "(I) set_gateway: arg_if: '$arg_if', arg_gw: '$arg_gw'"


set_gw() {
  ip=$2
  [ -n "$ip" ] && ip=",$ip"
  uci set dhcp.$1.dhcp_option="3$ip"
}

if [ "$arg_if" = "mesh" ]
then #called by /etc/hotplug.d/net/11-batman
    mesh_gw="$arg_gw"
    local_gw=$pre_local_gw
else #called by /sbin/wan_watchdog
    mesh_gw=$pre_mesh_gw
    local_gw="$arg_gw"
fi

echo "(I) set_gateway: pre_mesh_gw: '$pre_mesh_gw', pre_local_gw: '$pre_local_gw'"

[ "$pre_mesh_gw" == "$mesh_gw" -a "$pre_local_gw" == "$local_gw" ] && {
  echo "(I) set_gateway: Nothing to change. - done"
  exit 0
}

echo "(I) set_gateway: mesh_gw: '$mesh_gw', local_gw: '$local_gw'"

echo -n "$local_gw" > /tmp/ff_local_gw
echo -n "$mesh_gw" > /tmp/ff_mesh_gw

#set gw to annouce in lan and mesh
share_wan=`uci get -q freifunk.settings.share_wan`
if [ "$share_wan" = "yes" ]; then
  if [ -n "$local_gw" ]; then
    set_gw "mesh" "$local_gw"
    set_gw "lan" "$local_gw"
  else
    set_gw "mesh" "$mesh_gw"
    set_gw "lan" "$mesh_gw"
  fi
else
  if [ -n "$local_gw" ]; then
    set_gw "mesh" "$mesh_gw"
    set_gw "lan" "$local_gw"
  else
    set_gw "mesh" "$mesh_gw"
    set_gw "lan" "$mesh_gw"
  fi
fi

#echo "(I) set_gateway: Remove all default routes."
#while true; do
#  route del default 2> /dev/null
#  [ $? -ne 0 ] && break
#done

#set local default gateway
#echo "(I) set_gateway: Set local default route to '$gw'."
#gw=`cat /tmp/state/network | sed -n -r 's/^.*lease_gateway=(.*)$/\1/p'`
#if [ -n "$local_gw" -a -n "$gw" ]; then
#    route add default gw $gw
#elif [ -n "$mesh_gw"]
#    route add default gw $mesh_gw
#fi

#killall -HUP dnsmasq
/etc/init.d/dnsmasq restart

echo "(I) set_gateway: done"
