#!/bin/sh

exec >/tmp/wan_watchdog.log 2>&1
date

echo "(I) wan_watchdog: start"

#various root servers
IPCHECK="192.33.4.12 128.8.10.90 193.0.14.129 198.41.0.4 192.228.79.201 192.5.5.241 192.36.148.17 192.58.128.30"

wan_interface=`uci -q get network.wan.ifname`
echo "(I) wan_watchdog: wan interface: '$wan_interface'"

bat_mode=`uci -q get batman-adv.bat0.gw_mode`
echo "(I) wan_watchdog: current batman mode: '$bat_mode'"

mesh_ip=`ifconfig br-mesh | grep "inet" | awk 'BEGIN { FS=":" } { print $2 }'| awk '{ print $1 }'`
echo "(I) wan_watchdog: current mesh ip: '$mesh_ip'"

#check if wan interface exists
if [ -z "$wan_interface" ]; then
  echo "(I) wan_watchdog: No WAN interface available. -> exit"
  exit 0
fi

#check if the node has a mesh ip
if [ -z "$mesh_ip" ]; then
  echo "(I) wan_watchdog: No mesh ip set. -> exit"
  exit 0
fi

#check if batman-adv is running
if [ $(ifconfig bat0 2> /dev/null | wc -l) == 0 ]; then
    echo "(I) wan_watchdog: batman-adv does not run. -> exit"
    exit 1
fi

wan_ip=`ifconfig $wan_interface | grep "inet" | awk 'BEGIN { FS=":" } { print $2 }'| awk '{ print $1 }'`

#check if the WAN interface has an IP address
if [ -z "$wan_ip" ]; then
  echo "(I) wan_watchdog: WAN interface has no IP - try to get one..."
  udhcpc -t 3 -n -q -i $wan_interface
  wan_ip=`ifconfig $wan_interface | grep "inet" | awk 'BEGIN { FS=":" } { print $2 }'| awk '{ print $1 }'`
else
    echo "(I) wan_watchdog: WAN IP is: '$wan_ip'"
fi


if [ -n "$wan_ip" -a $(fping -a $IPCHECK 2> /dev/null | wc -l) != 0 ]; then
    # we have internet
    if [ "$bat_mode" == "client" ]; then
        echo "(I) wan_watchdog: Switch to gateway mode."
        uci set batman-adv.bat0.gw_mode="server"
        batctl gw server
        /etc/init.d/nodogsplash start > /dev/null
    else
        echo "(I) wan_watchdog: Already in gateway mode."
    fi
else
    # we have no internet
    if [ "$bat_mode" == "server" ]; then
        echo "(I) wan_watchdog: Switch to client mode."
        uci set batman-adv.bat0.gw_mode="client"
        batctl gw client
        /etc/init.d/nodogsplash stop > /dev/null
    else
        echo "(I) wan_watchdog: Already in client mode."
    fi
fi

echo "(I) wan_watchdog: done"
