#!/bin/sh

[ "$INTERFACE" = "public6" ] || exit
  
. /lib/functions/network.sh

dnsservers=""
network_get_dnsserver dnsservers public6 true

echo > /tmp/resolv.conf.public.auto
for dnsserver in $dnsservers; do
	if [ "$(ip a | grep -c $dnsserver)" = "0" ]; then
		echo "nameserver $dnsserver" >> /tmp/resolv.conf.public.auto
	fi
done
