#!/bin/sh

[ "$INTERFACE" = "public6" ] || exit
  
. /lib/functions/network.sh

dnsserver=""
network_get_dnsserver dnsserver public6

if [ -n "$dnsserver" ]; then
	echo "nameserver $dnsserver" > /tmp/resolv.conf.public.auto
fi
