#!/bin/sh

[ "$INTERFACE" = "freifunk6" ] || exit
  
. /lib/functions/network.sh

dnsservers=""
network_get_dnsserver dnsservers freifunk6 true

echo > /tmp/resolv.conf.freifunk.auto
for dnsserver in $dnsservers; do
	if [ "$(ip a | grep -c $dnsserver)" = "0" ]; then
		echo "nameserver $dnsserver" >> /tmp/resolv.conf.freifunk.auto
	fi
done
