#!/bin/sh
echo -en "Cache-Control: no-cache, max-age=0, no-store, must-revalidate\r\n"
echo -en "Pragma: no-cache\r\n"
echo -en "Expires: -1\r\n"
echo -en "Status: 302 Temporary Redirect\r\n"
echo -en "Location: http://"`uci get network.mesh.ipaddr`"/cgi-bin/splash?http://"`echo $HTTP_HOST$REQUEST_URI`"\r\n"
echo -en "\r\n"
exit 0
