#!/bin/sh
echo -en "Status: 200 OK\r\n"
echo -en "Content-Type: text/html\r\n"
echo -en "\r\n"
                                    
. $IPKG_INSTROOT/etc/functions.sh
ISSPLASHED=0
config_load splash_users
is_ip() {
   config_get ip "$1" ip
   if [ "$ip" == "$REMOTE_HOST" ]; then
   	ISSPLASHED=1
   fi
}
#check if user is alredy splashed
config_foreach is_ip user
targeturl=$(echo $QUERY_STRING | sed 's/+/ /g; s/%/\\x/g')
sed "s/targeturl/"$targeturl"/g" /www/iframe.html

if [ $ISSPLASHED -eq 1 ]; then
	exit
fi
#User is now free to go
iptables  -t nat -I ffj_splash 1 -s $REMOTE_HOST -j ACCEPT

uci add splash_users user
uci set splash_users.@user[-1].ip=$REMOTE_HOST
uci set splash_users.@user[-1].time=`date +%s`
uci -q commit > /dev/null
exit 0


                                               

